version: "3.8"

services:
  jobson-app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: jobson_application
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - jobson-network

networks:
  jobson-network:
