version: "3.8"

services:
  jobson-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile.development # Updated path
    container_name: jobson_application
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - jobson-network
    volumes:
      - .:/usr/src/app

  streamlit-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile.Streamlit # Updated path
    container_name: jobson_streamlit_application
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - jobson-network

networks:
  jobson-network:
    driver: bridge
