# app/config.py
import os
from dotenv import load_dotenv

load_dotenv()


class Config:
    """Application configuration settings."""

    API_KEY = os.getenv("API_KEY")
    BASE_URL = "https://serpapi.com/search.json"
    MONGO_URI = os.getenv("MONGO_URI")
    PORT = os.getenv("PORT")

    JOB_QUERIES = [
        "Engenheiro de Software",
        "Cientista de Dados",
        "Gerente de Projetos",
        "Engenheiro DevOps",
        "Desenvolvedor Frontend",
        "Desenvolvedor Backend",
        "Desenvolvedor Full Stack",
        "Desenvolvedor Mobile",
        "Analista de Dados",
        "Analista de Sistemas",
        "Administrador de Redes",
        "Administrador de Banco de Dados",
        "Especialista em Suporte de TI",
        "Analista de Segurança",
        "Engenheiro de Nuvem",
    ]

    BRAZILIAN_STATES = [
        "Acre",
        "Alagoas",
        "Amapá",
        "Amazonas",
        "Bahia",
        "Ceará",
        "Distrito Federal",
        "Espírito Santo",
        "Goiás",
        "Maranhão",
        "Mato Grosso",
        "Mato Grosso do Sul",
        "Minas Gerais",
        "Pará",
        "Paraíba",
        "Paraná",
        "Pernambuco",
        "Piauí",
        "Rio de Janeiro",
        "Rio Grande do Norte",
        "Rio Grande do Sul",
        "Rondônia",
        "Roraima",
        "Santa Catarina",
        "São Paulo",
        "Sergipe",
        "Tocantins",
    ]

    REMOTE_WORK_TERMS = [
        "remote",
        "work from home",
        "trabajo remoto",
        "trabajar desde casa",
        "trabalho remoto",
        "trabalhar de casa",
        "home office",
    ]

    SKILL_LIST = [
        "Python",
        "Java",
        "SQL",
        "NoSQL",
        "Git",
        "JavaScript",
        "HTML",
        "CSS",
        "React",
        "Angular",
        "Vue.js",
        "Node.js",
        "Docker",
        "Kubernetes",
        "AWS",
        "Azure",
        "GCP",
        "Linux",
        "Bash",
        "PowerShell",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Data Analysis",
        "Data Visualization",
        "Pandas",
        "NumPy",
        "SciPy",
        "Matplotlib",
        "Seaborn",
        "Project Management",
        "Agile",
        "Scrum",
        "Kanban",
        "DevOps",
        "CI/CD",
        "Jenkins",
        "Travis CI",
        "GitLab CI",
        "CircleCI",
        "Networking",
        "Security",
        "Cloud Computing",
        "Mobile Development",
        "iOS",
        "Android",
        "Swift",
        "Kotlin",
        "React Native",
        "Flutter",
        "Frontend Development",
        "Backend Development",
        "Full Stack Development",
        "Web Development",
        "PHP",
        "Ruby on Rails",
        "Django",
        "Flask",
        "Spring Boot",
        ".NET",
        "C#",
        "Go",
        "Rust",
        "Support",
        "Troubleshooting",
        "Database Management",
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "Cassandra",
        "Redis",
        "Elasticsearch",
        "GraphQL",
        "REST",
        "SOAP",
        "Microservices",
        "API Design",
        "System Design",
        "Architecture Patterns",
        "Design Patterns",
        "SOLID Principles",
        "TDD",
        "BDD",
        "FDD",
        "XP",
        "Continuous Integration",
        "Continuous Deployment",
        "Infrastructure as Code",
        "Terraform",
        "Ansible",
        "CloudFormation",
        "Puppet",
        "Chef",
        "Virtualization",
        "VMware",
        "Hyper-V",
        "VirtualBox",
        "Data Science",
        "Statistics",
        "Big Data",
        "Hadoop",
        "Spark",
        "Flink",
        "Data Mining",
        "ETL",
        "Data Warehousing",
        "Business Intelligence",
        "Tableau",
        "Power BI",
        "Qlik",
        "Communication",
        "Teamwork",
        "Problem-Solving",
        "Critical Thinking",
        "Leadership",
        "Time Management",
        "Adaptability",
        "Creativity",
        "Work Ethic",
        "Interpersonal Skills",
        "Emotional Intelligence",
        "Customer Service",
        "Sales",
        "Marketing",
        "SEO",
        "Content Creation",
        "Digital Marketing",
        "Social Media Marketing",
        "Email Marketing",
        "Network Administration",
        "System Administration",
        "Firewall Management",
        "VPN",
        "IDS/IPS",
        "Penetration Testing",
        "Vulnerability Assessment",
        "Cybersecurity",
        "Information Security",
        "ISO 27001",
        "NIST Framework",
        "GDPR Compliance",
        "Blockchain",
        "Smart Contracts",
        "Ethereum",
        "Bitcoin",
        "Cryptography",
        "AI Ethics",
        "Quantum Computing",
        "IoT",
        "Edge Computing",
        "Augmented Reality",
        "Virtual Reality",
        "UI/UX Design",
        "Photoshop",
        "Illustrator",
        "Sketch",
        "Figma",
        "Wireframing",
        "Prototyping",
        "User Research",
        "A/B Testing",
        "Conversion Rate Optimization",
        "Accessibility",
        "Performance Optimization",
        "Scalability",
        "Load Testing",
        "Stress Testing",
        "Security Testing",
    ]
