version: "3.8"

services:
  jobson-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobson_application
    restart: unless-stopped
    ports:
      - "3500:3500"
    env_file:
      - .env
    networks:
      - jobson-network
    depends_on:
      - jobson-mongo

  jobson-mongo:
    image: mongo:latest
    container_name: jobson_mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - jobson-mongo-data:/data/db
    networks:
      - jobson-network

volumes:
  jobson-mongo-data:

networks:
  jobson-network:
